### ISSUE TITLE
Use of undeclared identifier 'DBL_MAX'

### ISSUE THREAD

**Issue by Bruno-Furtado** [acoomans/Parallax#8]
**xcodebuild error**
- error: use of undeclared identifier 'DBL_MAX'

Parallax/Parallax/ACAttitude.m:12:60
Parallax/Parallax/ACAttitude.m:12:77
Parallax/Parallax/ACAttitude.m:12:93

**Comment by acoomans** [comment]
I can't reproduce the error but commit #9462cb5d70e984b42d38f536d762ebdf3c4c7eab should fix it.

**Comment by Bruno-Furtado** [comment]
Bug fixed.
I'm changing the version of podspec and sending the changes in another pull request.

Thanks!
